version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  files:
    - 'template.yml'
    - 'scripts/**/*'
    - 'helloworld/**/*'
    - 'uploads/**/*'
    - 'helloworld/**/*.py'
    - 'helloworld/**/*.html'
    - 'helloworld/**/*.css'
    - 'helloworld/**/*.js'
    - 'helloworld/**/*.jpg'
    - 'helloworld/**/*.jpeg'
    - 'helloworld/**/*.png'
    - 'helloworld/**/*.ico'
    - 'appspec.yml'
    - 'requirements.txt'
    - 'setup.py'
    - 'template-configuration.json'
